# Generated by Django 4.1.1 on 2022-09-25 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('name', models.TextField()),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DigitalItem',
            fields=[
                ('saleitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='motivator_site.saleitem')),
                ('promo_codes', models.TextField()),
            ],
            bases=('motivator_site.saleitem',),
        ),
        migrations.CreateModel(
            name='PhysicalItem',
            fields=[
                ('saleitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='motivator_site.saleitem')),
                ('count', models.PositiveIntegerField()),
                ('is_inifity', models.BooleanField()),
            ],
            bases=('motivator_site.saleitem',),
        ),
    ]
