# Generated by Django 4.1.1 on 2022-09-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motivator_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='physicalitem',
            old_name='is_inifity',
            new_name='is_infinity',
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
