# Generated by Django 4.1.1 on 2022-09-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motivator_site', '0002_rename_is_inifity_physicalitem_is_infinity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
