# Generated by Django 4.1.1 on 2022-09-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motivator_site', '0003_alter_saleitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='image',
            field=models.ImageField(upload_to='images/motivator/'),
        ),
    ]
