"""
Django settings for settings project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from decouple import config
from urllib.parse import urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY", None, cast=str)

# APPEND_SLASH=False
AUTH_USER_MODEL = 'auth.UserModel'

LOGIN_URL = '/auth'
LOGIN_REDIRECT_URL = '/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)

INTERNET_URL = config("INTERNET_URL", default='http://127.0.0.1:8000')
INTERNET_DOMAIN = urlparse(INTERNET_URL).netloc

USE_SECURE_HTTPS = config("USE_SECURE_HTTPS", default=False, cast=bool)
if not USE_SECURE_HTTPS:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


ALLOWED_HOSTS = [ '*' ]

# Application definition

INSTALLED_APPS = [
    'auth.apps.AuthConfig',
    'routes.apps.RoutesConfig',
    'dashboard.apps.Config',
    
    # 'django.contrib.admin',
    # 'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.contenttypes',
    'django.contrib.staticfiles',
    'crispy_forms',
    'django.forms'
]

MIDDLEWARE = [
    # 'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django.contrib.messages.middleware.MessageMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    'auth.middleware.csrf_middleware.CsrfMiddleware',
]

ROOT_URLCONF = 'settings.urls'

FORM_RENDERER = 'django.forms.renderers.TemplatesSetting'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
            BASE_DIR / 'widgets/templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                # 'django.contrib.auth.context_processors.auth',
                # 'django.contrib.messages.context_processors.messages',
                
                "settings.context_processors.settings_context",
            ],
        },
    },
]

WSGI_APPLICATION = 'settings.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'roket_team',
        'USER': 'roket_team',
        'PASSWORD': '8awf3oHn4X4fWZY1',
        'HOST': 'localhost',
        'PORT': '3306',
    }
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': (
    #         config("DATABASE_PATH", default=None) 
    #         or (
    #             BASE_DIR / 'database.db'
    #         )
    #     ),
    # }
}

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

SECURE_CROSS_ORIGIN_OPENER_POLICY = None

SESSION_ENGINE = 'auth.db.session_engine'

SESSION_COOKIE_NAME = "session_id"
SESSION_COOKIE_AGE = timedelta(days=14).total_seconds()
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

CSRF_COOKIE_NAME = "csrf_token"
CSRF_COOKIE_AGE = timedelta(days=5).total_seconds()

CSRF_IGNORE_PATHS = [
    "/@/web_shop/",
    "/@/slack/",
]

if USE_SECURE_HTTPS:
    SESSION_COOKIE_SAMESITE = 'Lax'
    # SESSION_COOKIE_DOMAIN = INTERNET_DOMAIN
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SECURE = True

    CSRF_COOKIE_SAMESITE = 'Lax'
    # CSRF_COOKIE_DOMAIN = INTERNET_DOMAIN
    CSRF_COOKIE_HTTPONLY = True
    CSRF_COOKIE_SECURE = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

CRISPY_TEMPLATE_PACK = 'bootstrap4'

STATIC_URL = "/static/"
MEDIA_URL = "/media/"

STATIC_ROOT = BASE_DIR / "static"
MEDIA_ROOT = BASE_DIR / "media"


# TOKENS Side
SLACK_BOT_UUID = config("SLACK_BOT_UUID", default=None, cast=str)
SLACK_VERIFICATION_TOKEN = config("SLACK_VERIFICATION_TOKEN", default=None, cast=str)
SLACK_ACCESS_TOKEN = config("SLACK_ACCESS_TOKEN", default=None, cast=str)

TELEGRAM_BOT_TOKEN = config("TELEGRAM_BOT_TOKEN", default=None, cast=str)
