# Generated by Django 3.2.16 on 2022-10-26 06:25

import django.contrib.sessions.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.IntegerField(db_index=True, null=True, unique=True)),
                ('tg_login', models.CharField(max_length=100, null=True)),
                ('full_name', models.CharField(max_length=170, null=True)),
                ('status', models.CharField(choices=[('BLOCK', 'Blocked'), ('DELETE', 'Deleted'), ('GR_ADM', 'Gr Admin'), ('SUP_ADM', 'Owner')], default='GR_ADM', max_length=15)),
                ('user_identity_token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sys_users',
            },
        ),
        migrations.CreateModel(
            name='SessionModel',
            fields=[
                ('session_data', models.TextField(verbose_name='session data')),
                ('session_key', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='session key')),
                ('csrf_token', models.CharField(max_length=60, null=True, verbose_name='csrf token')),
                ('expire_date', models.DateTimeField(db_index=True, null=True, verbose_name='expire date')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='auth.usermodel')),
            ],
            options={
                'verbose_name': 'session',
                'verbose_name_plural': 'sessions',
                'db_table': 'sys_session',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.sessions.models.SessionManager()),
            ],
        ),
    ]
