# Generated by Django 3.2.15 on 2022-09-29 16:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0002_alter_usermodel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.IntegerField(db_index=True)),
                ('login', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('user_token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('state', models.CharField(choices=[('NORMAL', 'Normal'), ('LEAVE', 'Leave')], default='NORMAL', max_length=15)),
                ('current_balance', models.IntegerField(default=10)),
                ('safe_balance', models.IntegerField(default=0)),
                ('clear_time', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'tg_bot_users',
            },
        ),
        migrations.CreateModel(
            name='BotWebChatShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/motivator/')),
                ('name', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField(default=0)),
                ('count', models.PositiveIntegerField(default=0)),
                ('promo_codes', models.TextField(null=True)),
                ('is_infinity', models.BooleanField(default=False)),
                ('item_type', models.CharField(choices=[('REAL', 'Real'), ('VIRTUAL', 'Virtual')], default='REAL', max_length=20)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.botusermodel')),
            ],
            options={
                'db_table': 'tg_web_chat_shop',
            },
        ),
        migrations.CreateModel(
            name='BotWebChatShopHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_issued', models.BooleanField(default=False)),
                ('buy_time', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.botwebchatshop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.botusermodel')),
            ],
            options={
                'db_table': 'tg_web_chat_shop_history',
            },
        ),
        migrations.CreateModel(
            name='BotTransferHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('transfer_time', models.DateTimeField(auto_now=True)),
                ('u_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spends', to='dashboard.botusermodel')),
                ('u_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refills', to='dashboard.botusermodel')),
            ],
            options={
                'db_table': 'tg_bot_transfer_history',
            },
        ),
        migrations.CreateModel(
            name='BotChatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.IntegerField(db_index=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('join_time', models.DateTimeField(auto_now=True)),
                ('admins', models.ManyToManyField(related_name='chats', to='auth.UserModel')),
                ('users', models.ManyToManyField(related_name='chats', to='dashboard.BotUserModel')),
            ],
            options={
                'db_table': 'tg_bot_chats',
            },
        ),
    ]
